
import React from 'react';
import { Language } from './types';

export const TRANSLATIONS = {
  [Language.EN]: {
    appName: "FAM ROOM",
    welcome: "Welcome to Fam Room",
    selectLang: "Select Language",
    login: "Sign In",
    signup: "Sign Up",
    email: "Email Address",
    password: "Password",
    forgotPassword: "Forgot Password?",
    resetPassword: "Reset Password",
    sendResetLink: "Send Reset Link",
    backToLogin: "Back to Login",
    checkEmailReset: "Check your email for the reset link!",
    noAccount: "Don't have an account?",
    hasAccount: "Already have an account?",
    enterPhone: "Enter Phone Number",
    enterOtp: "Enter 6-digit OTP",
    verify: "Get OTP",
    verifyCode: "Verify & Login",
    rememberMe: "Remember Me",
    otpSent: "OTP sent to",
    setUsername: "What is your name?",
    createRoom: "Create Family Room",
    joinRoom: "Join Family Room",
    roomName: "Family Room Name",
    joinCode: "Enter Join Code",
    admin: "Admin",
    young: "Young",
    elder: "Elder",
    meds: "Medicines",
    checkIn: "Check-in",
    sos: "SOS",
    callFamily: "Call Family",
    chat: "Family Chat",
    members: "Members",
    logs: "History",
    settings: "Settings",
    emergencyAlert: "EMERGENCY!",
    sosCallNotice: "Automatic call in 5 mins",
    medReminder: "Time for Medicine",
    done: "Done",
    confirmCheckIn: "I am doing well!",
    send: "Send",
    placeholderMsg: "Type a message...",
    noRoom: "You are not in a family room yet."
  },
  [Language.HI]: {
    appName: "फैम रूम",
    welcome: "फैम रूम में आपका स्वागत है",
    selectLang: "भाषा चुनें",
    login: "साइन इन करें",
    signup: "साइन अप करें",
    email: "ईमेल एड्रेस",
    password: "पासवर्ड",
    forgotPassword: "पासवर्ड भूल गए?",
    resetPassword: "पासवर्ड रीसेट करें",
    sendResetLink: "रीसेट लिंक भेजें",
    backToLogin: "लॉगिन पर वापस जाएं",
    checkEmailReset: "रीसेट लिंक के लिए अपना ईमेल देखें!",
    noAccount: "अकाउंट नहीं है?",
    hasAccount: "पहले से अकाउंट है?",
    enterPhone: "फोन नंबर डालें",
    enterOtp: "6-अंकों का ओटीपी डालें",
    verify: "ओटीपी प्राप्त करें",
    verifyCode: "सत्यापित करें और लॉगिन करें",
    rememberMe: "मुझे याद रखें",
    otpSent: "ओटीपी भेजा गया है",
    setUsername: "आपका नाम क्या है?",
    createRoom: "फैमिली रूम बनाएं",
    joinRoom: "फैमिली रूम में शामिल हों",
    roomName: "फैमिली रूम का नाम",
    joinCode: "जॉइन कोड डालें",
    admin: "एडमिन",
    young: "युवा",
    elder: "बुजुर्ग",
    meds: "दवाइयां",
    checkIn: "चेक-इन",
    sos: "एसओएस (आपातकालीन)",
    callFamily: "परिवार को कॉल करें",
    chat: "फैमिली चैट",
    members: "सदस्य",
    logs: "इतिहास",
    settings: "सेटिंग्स",
    emergencyAlert: "आपातकालीन!",
    sosCallNotice: "5 मिनट में ऑटोमैटिक कॉल",
    medReminder: "दवाई का समय",
    done: "हो गया",
    confirmCheckIn: "मैं ठीक हूँ!",
    send: "भेजें",
    placeholderMsg: "संदेश लिखें...",
    noRoom: "आप अभी तक किसी फैमिली रूम में नहीं हैं।"
  }
};
